### ISSUE TITLE
Recipe App Kanban board setup

### ISSUE THREAD

**Issue by Nemwel-Boniface** [moise-mulungu/Recipe_app#11]
## Hello reviewer(s)
This is @moise-mulungu, and @Nemwel-Boniface team :sunglasses: 
We are a team of two. In this milestone, we were able to set up the Kanban board which can be viewed [here](https://github.com/users/moise-mulungu/projects/4/views/1).

Our Recipe App project is divided among us in this order:

1. @moise-mulungu  is Team member 1 tacking the Recipe lists
2. @Nemwel-Boniface is Team member 2 tackling the Foods lists
3. The recipe food is set as a group task
4. The General shopping list is set as a group task

Thank you for taking the time to review our project :pray:

**Comment by addod19** [comment]
### Hi @Nemwel-Boniface and @moise-mulungu, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- [ ] Projects equally shared among collaborators :+1: 
- [ ] Each card has title, description, and pt :100: 
- [ ] All cards are assigned to members, awesome :1st_place_medal: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
